"use strict";
// BlackPyre data payload — classic script, loaded before the main app script.
// Shares the global scope by design (no ES modules). See ARCHITECTURE.md.

const QUOTES = [
  // ===== the greats =====
  {q:"The last three or four reps is what makes the muscle grow.", a:"Arnold Schwarzenegger"},
  {q:"Everybody wants to be a bodybuilder, but nobody wants to lift no heavy-ass weights.", a:"Ronnie Coleman"},
  {q:"I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion.", a:"Muhammad Ali"},
  {q:"Today I will do what others won't, so tomorrow I can accomplish what others can't.", a:"Jerry Rice"},
  {q:"Strength does not come from winning. Your struggles develop your strengths.", a:"Arnold Schwarzenegger"},
  {q:"The successful warrior is the average man, with laser-like focus.", a:"Bruce Lee"},
  {q:"If you think lifting is dangerous, try being weak. Being weak is dangerous.", a:"Bret Contreras"},
  {q:"The pain you feel today will be the strength you feel tomorrow.", a:"Common gym wisdom"},
  {q:"Discipline is doing what you hate to do, but doing it like you love it.", a:"Mike Tyson"},
  {q:"You miss 100% of the shots you don't take.", a:"Wayne Gretzky"},
  {q:"A champion is someone who gets up when they can't.", a:"Jack Dempsey"},
  {q:"Success usually comes to those who are too busy to be looking for it.", a:"Henry David Thoreau"},
  {q:"The body achieves what the mind believes.", a:"Common training wisdom"},
  {q:"Don't count the days, make the days count.", a:"Muhammad Ali"},
  {q:"What hurts today makes you stronger tomorrow.", a:"Jay Cutler"},
  {q:"The worst thing I can be is the same as everybody else.", a:"Arnold Schwarzenegger"},
  {q:"You shall gain, but you shall pay with sweat, blood, and vomit.", a:"Pavel Tsatsouline"},
  {q:"There are no shortcuts. Everything is reps, reps, reps.", a:"Arnold Schwarzenegger"},
  {q:"Champions aren't made in gyms. Champions are made from something deep inside them: a desire, a dream, a vision.", a:"Muhammad Ali"},
  {q:"Hard work beats talent when talent doesn't work hard.", a:"Tim Notke"},
  {q:"If it doesn't challenge you, it doesn't change you.", a:"Fred DeVito"},
  {q:"We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a:"Will Durant"},
  {q:"Whether you think you can, or you think you can't — you're right.", a:"Henry Ford"},
  {q:"He who is not courageous enough to take risks will accomplish nothing in life.", a:"Muhammad Ali"},
  {q:"It isn't the mountains ahead to climb that wear you out; it's the pebble in your shoe.", a:"Muhammad Ali"},
  {q:"I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", a:"Bruce Lee"},
  {q:"Do not pray for an easy life; pray for the strength to endure a difficult one.", a:"Bruce Lee"},
  {q:"Long-term consistency trumps short-term intensity.", a:"Bruce Lee"},
  {q:"A goal is not always meant to be reached; it often serves simply as something to aim at.", a:"Bruce Lee"},
  {q:"You have power over your mind — not outside events. Realize this, and you will find strength.", a:"Marcus Aurelius"},
  {q:"The impediment to action advances action. What stands in the way becomes the way.", a:"Marcus Aurelius"},
  {q:"Waste no more time arguing about what a good man should be. Be one.", a:"Marcus Aurelius"},
  {q:"It is not death that a man should fear, but he should fear never beginning to live.", a:"Marcus Aurelius"},
  {q:"Confine yourself to the present.", a:"Marcus Aurelius"},
  {q:"The soul becomes dyed with the color of its thoughts.", a:"Marcus Aurelius"},
  {q:"It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.", a:"Seneca"},
  {q:"Difficulties strengthen the mind, as labor does the body.", a:"Seneca"},
  {q:"Luck is what happens when preparation meets opportunity.", a:"Seneca"},
  {q:"He suffers more than necessary, who suffers before it is necessary.", a:"Seneca"},
  {q:"No man was ever wise by chance.", a:"Seneca"},
  {q:"No man is free who is not master of himself.", a:"Epictetus"},
  {q:"First say to yourself what you would be; and then do what you have to do.", a:"Epictetus"},
  {q:"It's not what happens to you, but how you react to it that matters.", a:"Epictetus"},
  {q:"It is a shame for a man to grow old without seeing the beauty and strength of which his body is capable.", a:"Socrates"},
  {q:"The first and greatest victory is to conquer yourself.", a:"Plato"},
  {q:"Character is destiny.", a:"Heraclitus"},
  {q:"Dripping water hollows out stone, not through force but through persistence.", a:"Ovid"},
  {q:"Take rest; a field that has rested gives a bountiful crop.", a:"Ovid"},
  {q:"Fortune favors the bold.", a:"Virgil"},
  {q:"Practice is the best of all instructors.", a:"Publilius Syrus"},
  {q:"No one knows what he can do till he tries.", a:"Publilius Syrus"},
  {q:"Slow and steady wins the race.", a:"Aesop"},
  {q:"Little by little does the trick.", a:"Aesop"},
  {q:"It does not matter how slowly you go as long as you do not stop.", a:"Confucius"},
  {q:"The man who moves a mountain begins by carrying away small stones.", a:"Confucius"},
  {q:"Our greatest glory is not in never falling, but in rising every time we fall.", a:"Confucius"},
  {q:"A journey of a thousand miles begins with a single step.", a:"Lao Tzu"},
  {q:"Victorious warriors win first and then go to war.", a:"Sun Tzu"},
  {q:"In the midst of chaos, there is also opportunity.", a:"Sun Tzu"},
  {q:"Fall seven times, stand up eight.", a:"Japanese proverb"},
  {q:"Vision without action is a daydream. Action without vision is a nightmare.", a:"Japanese proverb"},
  {q:"The best time to plant a tree was twenty years ago. The second best time is now.", a:"Chinese proverb"},
  {q:"Smooth seas do not make skillful sailors.", a:"African proverb"},
  {q:"That which does not kill us makes us stronger.", a:"Friedrich Nietzsche"},
  {q:"Walking is man's best medicine.", a:"Hippocrates"},
  {q:"Do what you can, with what you have, where you are.", a:"Theodore Roosevelt"},
  {q:"The credit belongs to the man who is actually in the arena.", a:"Theodore Roosevelt"},
  {q:"Nothing in this world can take the place of persistence.", a:"Calvin Coolidge"},
  {q:"Energy and persistence conquer all things.", a:"Benjamin Franklin"},
  {q:"Well done is better than well said.", a:"Benjamin Franklin"},
  {q:"You may delay, but time will not.", a:"Benjamin Franklin"},
  {q:"If there is no struggle, there is no progress.", a:"Frederick Douglass"},
  {q:"Nothing ever comes to one, that is worth having, except as a result of hard work.", a:"Booker T. Washington"},
  {q:"I am a slow walker, but I never walk back.", a:"Abraham Lincoln"},
  {q:"Never give in — never, never, never.", a:"Winston Churchill"},
  {q:"Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.", a:"Helen Keller"},
  {q:"Optimism is the faith that leads to achievement.", a:"Helen Keller"},
  {q:"Do the thing and you shall have the power.", a:"Ralph Waldo Emerson"},
  {q:"That which we persist in doing becomes easier for us to do.", a:"Ralph Waldo Emerson"},
  {q:"Act as if what you do makes a difference. It does.", a:"William James"},
  {q:"Great works are performed not by strength but by perseverance.", a:"Samuel Johnson"},
  {q:"All things are difficult before they are easy.", a:"Thomas Fuller"},
  {q:"The secret of success is constancy to purpose.", a:"Benjamin Disraeli"},
  {q:"Genius is one percent inspiration and ninety-nine percent perspiration.", a:"Thomas Edison"},
  {q:"Many of life's failures are people who did not realize how close they were to success when they gave up.", a:"Thomas Edison"},
  {q:"Opportunity is missed by most people because it is dressed in overalls and looks like work.", a:"Thomas Edison"},
  {q:"The most difficult thing is the decision to act; the rest is merely tenacity.", a:"Amelia Earhart"},
  {q:"Accept the challenges so that you can feel the exhilaration of victory.", a:"George S. Patton"},
  {q:"Strength and growth come only through continuous effort and struggle.", a:"Napoleon Hill"},
  {q:"Patience, persistence and perspiration make an unbeatable combination for success.", a:"Napoleon Hill"},
  {q:"Courage is grace under pressure.", a:"Ernest Hemingway"},
  {q:"Nothing will work unless you do.", a:"Maya Angelou"},
  {q:"You must do the thing you think you cannot do.", a:"Eleanor Roosevelt"},
  {q:"With the new day comes new strength and new thoughts.", a:"Eleanor Roosevelt"},
  {q:"Never give up, for that is just the place and time that the tide will turn.", a:"Harriet Beecher Stowe"},
  {q:"Life is not easy for any of us. But what of that? We must have perseverance.", a:"Marie Curie"},
  {q:"Strength does not come from physical capacity. It comes from an indomitable will.", a:"Mahatma Gandhi"},
  {q:"Discipline is the bridge between goals and accomplishment.", a:"Jim Rohn"},
  {q:"Take care of your body. It's the only place you have to live.", a:"Jim Rohn"},
  {q:"Motivation is what gets you started. Habit is what keeps you going.", a:"Jim Ryun"},
  {q:"You don't have to be great to start, but you have to start to be great.", a:"Zig Ziglar"},
  {q:"Winners never quit and quitters never win.", a:"Vince Lombardi"},
  {q:"It's not whether you get knocked down; it's whether you get up.", a:"Vince Lombardi"},
  {q:"Perfection is not attainable, but if we chase perfection we can catch excellence.", a:"Vince Lombardi"},
  {q:"Once you learn to quit, it becomes a habit.", a:"Vince Lombardi"},
  {q:"Don't let what you cannot do interfere with what you can do.", a:"John Wooden"},
  {q:"Failing to prepare is preparing to fail.", a:"John Wooden"},
  {q:"Make each day your masterpiece.", a:"John Wooden"},
  {q:"Little things make big things happen.", a:"John Wooden"},
  {q:"The true test of a man's character is what he does when no one is watching.", a:"John Wooden"},
  {q:"Build up your weaknesses until they become your strong points.", a:"Knute Rockne"},
  {q:"Every strike brings me closer to the next home run.", a:"Babe Ruth"},
  {q:"It's hard to beat a person who never gives up.", a:"Babe Ruth"},
  {q:"We all have dreams. But in order to make dreams come into reality, it takes an awful lot of determination, dedication, self-discipline, and effort.", a:"Jesse Owens"},
  {q:"Never underestimate the power of dreams and the influence of the human spirit.", a:"Wilma Rudolph"},
  {q:"To give anything less than your best is to sacrifice the gift.", a:"Steve Prefontaine"},
  {q:"If you want to run, run a mile. If you want to experience a different life, run a marathon.", a:"Emil Zátopek"},
  {q:"When you're good at something, you'll tell everyone. When you're great at something, they'll tell you.", a:"Walter Payton"},
  {q:"Start where you are. Use what you have. Do what you can.", a:"Arthur Ashe"},
  {q:"Exercise is king. Nutrition is queen. Put them together and you've got a kingdom.", a:"Jack LaLanne"},
  {q:"Anything in life is possible if you make it happen.", a:"Jack LaLanne"},
  {q:"Nobody who ever gave his best regretted it.", a:"George Halas"},
  {q:"It's not the will to win that matters — everyone has that. It's the will to prepare to win that matters.", a:"Bear Bryant"},
  {q:"Mind is everything. Muscle — pieces of rubber. All that I am, I am because of my mind.", a:"Paavo Nurmi"},
  {q:"The man who can drive himself further once the effort gets painful is the man who will win.", a:"Roger Bannister"},
  {q:"Gold medals aren't really made of gold. They're made of sweat, determination, and a hard-to-find alloy called guts.", a:"Dan Gable"},
  {q:"I've failed over and over and over again in my life. And that is why I succeed.", a:"Michael Jordan"},
  {q:"Some people want it to happen, some wish it would happen, others make it happen.", a:"Michael Jordan"},
  {q:"You can't win unless you learn how to lose.", a:"Kareem Abdul-Jabbar"},
  {q:"Champions keep playing until they get it right.", a:"Billie Jean King"},
  {q:"It is more difficult to stay on top than to get there.", a:"Mia Hamm"},
  {q:"You can't get much done in life if you only work on the days when you feel good.", a:"Jerry West"},
  {q:"Excellence is the gradual result of always striving to do better.", a:"Pat Riley"},
  {q:"Set your goals high, and don't stop till you get there.", a:"Bo Jackson"},
  {q:"Setting a goal is not the main thing. It is deciding how you will go about achieving it and staying with that plan.", a:"Tom Landry"},
  {q:"It's not the load that breaks you down, it's the way you carry it.", a:"Lena Horne"},
  {q:"The only place where success comes before work is in the dictionary.", a:"Vidal Sassoon"},
  // ===== BlackPyre originals =====
  {q:"Motivation shows up sometimes. Discipline shows up daily.", a:"BlackPyre"},
  {q:"The bar doesn't care how you feel. Lift it anyway.", a:"BlackPyre"},
  {q:"Logged is better than perfect.", a:"BlackPyre"},
  {q:"You don't find time to train. You take it.", a:"BlackPyre"},
  {q:"Every rep you record is a promise you kept.", a:"BlackPyre"},
  {q:"The scale is data, not judgment.", a:"BlackPyre"},
  {q:"Consistency is the only supplement that always works.", a:"BlackPyre"},
  {q:"Heavy is relative. Showing up is absolute.", a:"BlackPyre"},
  {q:"A bad workout beats a skipped one every time.", a:"BlackPyre"},
  {q:"You are building a body no one can give you.", a:"BlackPyre"},
  {q:"The fire doesn't ask if you're ready.", a:"BlackPyre"},
  {q:"Steel is just iron that endured.", a:"BlackPyre"},
  {q:"Burn the excuse. Keep the lesson.", a:"BlackPyre"},
  {q:"Strong is a decision made daily.", a:"BlackPyre"},
  {q:"Nobody warms the bench at their own pyre.", a:"BlackPyre"},
  {q:"The work is quiet. The results are loud.", a:"BlackPyre"},
  {q:"Track it, or it never happened.", a:"BlackPyre"},
  {q:"Your future self is watching you train.", a:"BlackPyre"},
  {q:"Sore today. Sturdy tomorrow.", a:"BlackPyre"},
  {q:"The plate you load matters less than the day you don't skip.", a:"BlackPyre"},
  {q:"Numbers don't flatter. That's why they work.", a:"BlackPyre"},
  {q:"Progress hides in the boring weeks.", a:"BlackPyre"},
  {q:"You can't out-plan a workout you never start.", a:"BlackPyre"},
  {q:"Every session is a brick. Keep laying.", a:"BlackPyre"},
  {q:"The iron gives back exactly what you give it.", a:"BlackPyre"},
  {q:"Nothing forged comes out of a cold fire.", a:"BlackPyre"},
  {q:"Show up tired. Leave proud.", a:"BlackPyre"},
  {q:"The hardest set is the front door.", a:"BlackPyre"},
  {q:"Small plates, long months, big change.", a:"BlackPyre"},
  {q:"You don't need a new plan. You need another week of the old one.", a:"BlackPyre"},
  {q:"Your streak is a chain. Don't be the weak link in your own armor.", a:"BlackPyre"},
  {q:"Weigh in. Face it. Move on.", a:"BlackPyre"},
  {q:"Muscle is patience made visible.", a:"BlackPyre"},
  {q:"The gym rewards attendance before it rewards effort.", a:"BlackPyre"},
  {q:"Quit negotiating with the alarm.", a:"BlackPyre"},
  {q:"Nobody regrets the workout they finished.", a:"BlackPyre"},
  {q:"The pyre burns what you were. Keep what you're becoming.", a:"BlackPyre"},
  {q:"One more rep is a habit, not an accident.", a:"BlackPyre"},
  {q:"Your body keeps the receipts.", a:"BlackPyre"},
  {q:"Comfort is a debt. Training pays it down.", a:"BlackPyre"},
  {q:"Do the protein math before the excuse math.", a:"BlackPyre"},
  {q:"Discipline weighs ounces. Regret weighs tons.", a:"BlackPyre"},
  {q:"The log doesn't lie, and that's its gift.", a:"BlackPyre"},
  {q:"Rest is part of the program, not an escape from it.", a:"BlackPyre"},
  {q:"You're one meal from back on track.", a:"BlackPyre"},
  {q:"Strength is rented. Training is the rent.", a:"BlackPyre"},
  {q:"The mirror lags. The bar doesn't.", a:"BlackPyre"},
  {q:"Earn the shower.", a:"BlackPyre"},
  {q:"Every empty gym is full of the people who quit.", a:"BlackPyre"},
  {q:"Start heavy in spirit, light on the bar.", a:"BlackPyre"},
  {q:"A goal without a log is a wish.", a:"BlackPyre"},
  {q:"You don't rise to the occasion. You rise to your training.", a:"BlackPyre"},
  {q:"Grip the bar like you mean the rest of your life.", a:"BlackPyre"},
  {q:"The first set is a conversation. The last set is the truth.", a:"BlackPyre"},
  {q:"Cut the noise. Count the reps.", a:"BlackPyre"},
  {q:"Losing fat is math. Keeping at it is character.", a:"BlackPyre"},
  {q:"Your excuses don't lift. Neither do your critics.", a:"BlackPyre"},
  {q:"Train the body you have. Build the body you want.", a:"BlackPyre"},
  {q:"Momentum is made of Mondays.", a:"BlackPyre"},
  {q:"Sweat is the ink. The log is the story.", a:"BlackPyre"},
  {q:"The kitchen is half the gym.", a:"BlackPyre"},
  {q:"Slow progress is still a moving target — hard to stop.", a:"BlackPyre"},
  {q:"Lift like nobody's filming, because nobody is.", a:"BlackPyre"},
  {q:"The plateau is where the committed get sorted from the curious.", a:"BlackPyre"},
  {q:"Fuel like an athlete, not like a mood.", a:"BlackPyre"},
  {q:"Your last set this week is your first set next week.", a:"BlackPyre"},
  {q:"Nothing on a screen builds a back.", a:"BlackPyre"},
  {q:"Add five pounds. Subtract one excuse.", a:"BlackPyre"},
  {q:"A hard day trains the body. A boring day trains the will.", a:"BlackPyre"},
  {q:"You wanted results. The bar wants reps. Fair trade.", a:"BlackPyre"},
  {q:"The scale moves last. Move first.", a:"BlackPyre"},
  {q:"Every meal logged is a rep for your discipline.", a:"BlackPyre"},
  {q:"Show the plateau who keeps showing up.", a:"BlackPyre"},
  {q:"Iron sharpens iron. Sitting sharpens nothing.", a:"BlackPyre"},
  {q:"Strong backs are built on days you didn't feel like it.", a:"BlackPyre"},
  {q:"Half the battle is the gym bag by the door.", a:"BlackPyre"},
  {q:"The program works if you do.", a:"BlackPyre"},
  {q:"You can't delegate push-ups.", a:"BlackPyre"},
  {q:"Hunger fades. Quitting lingers.", a:"BlackPyre"},
  {q:"Be the reason your old shirts don't fit — in the good direction.", a:"BlackPyre"},
  {q:"Nobody is coming to lift it for you.", a:"BlackPyre"},
  {q:"Talent warms up. Work finishes.", a:"BlackPyre"},
  {q:"One honest weigh-in beats a week of guessing.", a:"BlackPyre"},
  {q:"The barbell is the most honest thing you'll touch today.", a:"BlackPyre"},
  {q:"You don't need easy. You need possible, then repeatable.", a:"BlackPyre"},
  {q:"Every PR was once a warm-up weight for somebody. Keep going.", a:"BlackPyre"},
  {q:"Skip the debate. Do the set.", a:"BlackPyre"},
  {q:"Two weeks of trend beats one day of feelings.", a:"BlackPyre"},
  {q:"Big engines are built in small garages.", a:"BlackPyre"},
  {q:"Your body hears everything your habits say.", a:"BlackPyre"},
  {q:"Deload the ego. Load the bar.", a:"BlackPyre"},
  {q:"Count macros like they're money, because they're worth more.", a:"BlackPyre"},
  {q:"A streak isn't luck. It's a decision on repeat.", a:"BlackPyre"},
  {q:"The couch will still be there. So will the consequences.", a:"BlackPyre"},
  {q:"Get under the bar. Get over yourself.", a:"BlackPyre"},
  {q:"Whatever today was, the log makes it count.", a:"BlackPyre"},
  {q:"Ten hard minutes beat sixty imagined ones.", a:"BlackPyre"},
  {q:"Strength is the slowest promise you'll ever keep — and the surest.", a:"BlackPyre"},
  {q:"The weights don't get lighter. You get harder to stop.", a:"BlackPyre"},
  {q:"Discipline is remembering why, mid-rep.", a:"BlackPyre"},
  {q:"Some days you beat the log. Some days you just don't let it beat you.", a:"BlackPyre"},
  {q:"Your goal weight is just gravity meeting consistency.", a:"BlackPyre"},
  {q:"Eat with a plan or eat your progress.", a:"BlackPyre"},
  {q:"Grit doesn't trend. It compounds.", a:"BlackPyre"},
  {q:"The pump fades by dinner. The habit doesn't.", a:"BlackPyre"},
  {q:"Nobody ever got strong by rescheduling.", a:"BlackPyre"},
  {q:"Treat the warm-up with respect. It's tomorrow's max.", a:"BlackPyre"},
  {q:"Write it down. Weight it down. Wear it proud.", a:"BlackPyre"},
  {q:"You've survived every hard set so far. The odds like you.", a:"BlackPyre"},
  {q:"There's no traffic on the extra mile at 5 a.m.", a:"BlackPyre"},
  {q:"Consistency looks boring right up until it looks incredible.", a:"BlackPyre"},
  {q:"Make the machine of you hard to turn off.", a:"BlackPyre"},
  {q:"Your knees, your back, your future — train them all on purpose.", a:"BlackPyre"},
  {q:"Do it tired. That's when it counts double.", a:"BlackPyre"},
  {q:"A month of honest logging beats a year of good intentions.", a:"BlackPyre"},
  {q:"The finish line moves. So do you. Advantage: you.", a:"BlackPyre"},
  {q:"Effort is a language. The log is how you write it down.", a:"BlackPyre"},
  {q:"Feed the goal, starve the doubt.", a:"BlackPyre"},
  {q:"Reps in the dark become strength in the light.", a:"BlackPyre"},
  {q:"You're not behind. You're in the middle of it.", a:"BlackPyre"},
  {q:"Trust the boring math: calories, protein, sleep, reps.", a:"BlackPyre"},
  {q:"Your body is the one project you can't outsource.", a:"BlackPyre"},
  {q:"Stack days like plates.", a:"BlackPyre"},
  {q:"Quiet grind. Loud results.", a:"BlackPyre"},
  {q:"Every legend has an off day in the log. None have an off month.", a:"BlackPyre"},
  {q:"You came this far on discipline. Don't switch fuels now.", a:"BlackPyre"},
  {q:"Weakness leaves one rep at a time.", a:"BlackPyre"},
  {q:"Do the work when it's dull. Cash it in when it matters.", a:"BlackPyre"},
  {q:"Tomorrow's warm-up was yesterday's PR. That's the whole plan.", a:"BlackPyre"},
  {q:"Log the meal you wish you hadn't eaten. Honesty is a macro too.", a:"BlackPyre"},
  {q:"When in doubt, show up. Doubt hates attendance.", a:"BlackPyre"},
  {q:"Hard now, strong later. Soft now, sorry later.", a:"BlackPyre"},
  {q:"The best program is the one you'll still be running in March.", a:"BlackPyre"},
  {q:"Your goals don't care about the weather.", a:"BlackPyre"},
  {q:"Somewhere your next PR is waiting, already loaded.", a:"BlackPyre"},
  {q:"You don't break plateaus. You outlast them.", a:"BlackPyre"},
  {q:"Sleep is a training day in disguise.", a:"BlackPyre"},
  {q:"Every glass of water is a small vote for the athlete in you.", a:"BlackPyre"},
  {q:"Take the stairs like they insulted you.", a:"BlackPyre"},
  {q:"Warm up the body. Fire up the intent.", a:"BlackPyre"},
  {q:"Champions are just people who kept excellent records and terrible excuses.", a:"BlackPyre"},
  {q:"The set you're dreading is the one that's working.", a:"BlackPyre"},
  {q:"Your only competition already trained today. It's yesterday's you.", a:"BlackPyre"},
  {q:"Strong isn't a look. It's a ledger.", a:"BlackPyre"},
  {q:"Turn discipline into identity and the alarm loses its power.", a:"BlackPyre"},
  {q:"Nobody drifts to a goal. You row.", a:"BlackPyre"},
  {q:"Protein first. Philosophy later.", a:"BlackPyre"},
  {q:"The last rep teaches what the first rep can't.", a:"BlackPyre"},
  {q:"Lift heavy things and heavy days get lighter.", a:"BlackPyre"},
  {q:"Track ruthlessly. Judge kindly. Continue regardless.", a:"BlackPyre"},
  {q:"You're not tired. You're almost done.", a:"BlackPyre"},
  {q:"Progress is loud in the log long before it's loud in the mirror.", a:"BlackPyre"},
  {q:"Build the habit so strong the bad day can't find the off switch.", a:"BlackPyre"},
  {q:"A real goal survives a bad week.", a:"BlackPyre"},
  {q:"Reps don't care about your mood, and that's mercy.", a:"BlackPyre"},
  {q:"Someday is not on the calendar. Today is.", a:"BlackPyre"},
  {q:"You've never once finished a workout and wished you hadn't.", a:"BlackPyre"},
  {q:"The fork sets the pace. The bar sets the shape.", a:"BlackPyre"},
  {q:"Endure the middle. Everyone claps at the end.", a:"BlackPyre"},
  {q:"Cold start, hot finish.", a:"BlackPyre"},
  {q:"Six months of ordinary makes extraordinary.", a:"BlackPyre"},
  {q:"Leave the gym with less doubt than you brought.", a:"BlackPyre"},
  {q:"Every skipped session votes for the old you.", a:"BlackPyre"},
  {q:"Do today what the goal requires, not what the mood suggests.", a:"BlackPyre"},
  {q:"You can rest at the top of the set, not the bottom of the couch.", a:"BlackPyre"},
  {q:"The strongest muscle is the one that decides.", a:"BlackPyre"},
  {q:"Numbers first. Feelings after. Results eventually. Always in that order.", a:"BlackPyre"},
  {q:"One clean week can turn a whole season.", a:"BlackPyre"},
  {q:"The grind doesn't need an audience.", a:"BlackPyre"},
  {q:"Bank the workout before the day can spend you.", a:"BlackPyre"},
  {q:"Nothing tastes as good as a kept promise.", a:"BlackPyre"},
  {q:"Let the log brag for you.", a:"BlackPyre"},
  {q:"Anger fades, hype fades, playlists end. The habit stays.", a:"BlackPyre"},
  {q:"Your spine remembers deadlift day. Make it a good memory.", a:"BlackPyre"},
  {q:"A tracked calorie is worth two guessed ones.", a:"BlackPyre"},
  {q:"Get comfortable being the last one breathing hard.", a:"BlackPyre"},
  {q:"The plan is written in ink. The excuses in pencil.", a:"BlackPyre"},
  {q:"Strength arrives on schedule for those who keep one.", a:"BlackPyre"},
  {q:"Miss a day, not a week. Miss a week, never a month.", a:"BlackPyre"},
  {q:"The forge doesn't rush and neither should you. It also never stops.", a:"BlackPyre"},
  {q:"Some build walls against hard things. You built a schedule.", a:"BlackPyre"},
  {q:"You are the project and the builder. Act like both.", a:"BlackPyre"},
  {q:"Chalk on the hands, plan in the head, doubt in the trash.", a:"BlackPyre"},
  {q:"There is no finish line — just heavier warm-ups.", a:"BlackPyre"},
  {q:"Prove it to the log before you promise it to anyone.", a:"BlackPyre"},
  {q:"Old you set the baseline. New you sets the record.", a:"BlackPyre"},
  {q:"A quiet no to the snack is a loud yes to the goal.", a:"BlackPyre"},
  {q:"Your habits are the crew. You're the captain. Steer.", a:"BlackPyre"},
  {q:"Everything heavy was impossible once.", a:"BlackPyre"},
  {q:"When the set gets loud in your head, get quiet in your grip.", a:"BlackPyre"},
  {q:"You don't need permission to be strong.", a:"BlackPyre"},
  {q:"The habit is the trophy. Everything else is engraving.", a:"BlackPyre"},
  {q:"Long after motivation clocks out, discipline works the night shift.", a:"BlackPyre"},
  {q:"Today's small win is tomorrow's normal.", a:"BlackPyre"},
  {q:"Guard the routine. It's guarding you back.", a:"BlackPyre"},
  {q:"Sweat now, swagger later.", a:"BlackPyre"},
  {q:"Nobody taps out of their own potential on your watch.", a:"BlackPyre"},
  {q:"Do the version of the workout that exists, not the one that's perfect.", a:"BlackPyre"},
  {q:"Your goal doesn't need you perfect. It needs you present.", a:"BlackPyre"},
  {q:"Count the wins the scale can't see.", a:"BlackPyre"},
  {q:"Show up like it's your job, because the results pay like one.", a:"BlackPyre"},
  {q:"The doubt was heavy too. You lifted that first.", a:"BlackPyre"},
  {q:"Keep the fire fed. Even embers forge steel, given time.", a:"BlackPyre"},
  {q:"Respect the light days. They carry the heavy ones.", a:"BlackPyre"},
  {q:"You measured it. Now you can move it.", a:"BlackPyre"},
  {q:"Grow through what you go through — preferably with a barbell.", a:"BlackPyre"},
  {q:"The calendar is undefeated. Team up with it.", a:"BlackPyre"},
  {q:"Fitness has no finish photo, only progress pictures.", a:"BlackPyre"},
  {q:"Turn 'I should' into 'I did' before noon.", a:"BlackPyre"},
  {q:"The weight room is a library. Every set, a page.", a:"BlackPyre"},
  {q:"Winners log their losses too.", a:"BlackPyre"},
  {q:"Appetite is a wave. Stand like a pier.", a:"BlackPyre"},
  {q:"Your PR list is a letter to your former self.", a:"BlackPyre"},
  {q:"Repetition is the mother of strength and the father of change.", a:"BlackPyre"},
  {q:"Don't chase the burn. Chase the log entry.", a:"BlackPyre"},
  {q:"Anyone can start a fire. Champions bank the coals.", a:"BlackPyre"},
  {q:"Do the next right rep.", a:"BlackPyre"},
  {q:"A strong grip on the bar starts with a strong grip on the day.", a:"BlackPyre"},
  {q:"Water, walks, weights, wins.", a:"BlackPyre"},
  {q:"You can't rush strength, but you can be on time for it.", a:"BlackPyre"},
  {q:"Missing a workout costs more than doing one.", a:"BlackPyre"},
  {q:"You brought yourself this far. Carry on.", a:"BlackPyre"},
  {q:"Tough sets, soft heart, hard to stop.", a:"BlackPyre"},
  {q:"Where focus goes, the barbell follows.", a:"BlackPyre"},
  {q:"Read the trend, not the Tuesday.", a:"BlackPyre"},
  {q:"Effort compounds. Excuses just accumulate.", a:"BlackPyre"},
  {q:"Even on your worst day, the log only asks for honesty.", a:"BlackPyre"},
  {q:"The strongest version of you is taking notes right now.", a:"BlackPyre"},
];
